spring:
  application:
    name: assignment
  datasource:
    url: jdbc:h2:mem:db
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none # 내장 db일 경우 기본값이 create-drop
    properties:
      hibernate:
        format_sql: true # SQL 포맷팅
        highlight_sql: true # ANSI 코드에 색 세팅
        use_sql_comments: true # SQL 내부에 /* */ 주석 추가
    defer-datasource-initialization: true

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace # 파라미터 값 출력
    org.springframework.jdbc.datasource.init: debug # schema.sql 실행 확인용