drop table if exists brand CASCADE;
create table brand
(
    id bigint generated by default as identity,
    brand_name varchar(255),
    created_date timestamp,
    last_modified_date timestamp,
    created_by varchar(255),
    last_modified_by varchar(255),
    primary key (id)
);
create unique index unique_brand_name on brand (brand_name);

drop table if exists category CASCADE;
create table category
(
    id bigint generated by default as identity,
    category_name varchar(255),
    sort_order int,
    created_date timestamp,
    last_modified_date timestamp,
    created_by varchar(255),
    last_modified_by varchar(255),
    primary key (id)
);
create unique index unique_category_name on category (category_name);

drop table if exists item CASCADE;
create table item
(
    id bigint generated by default as identity,
    price integer,
    brand_id bigint,
    category_id bigint,
    created_date timestamp,
    last_modified_date timestamp,
    created_by varchar(255),
    last_modified_by varchar(255),
    primary key (id)
);

alter table item
    add foreign key (brand_id)
        references brand(id);

alter table item
    add foreign key (category_id)
        references category(id);

CREATE UNIQUE INDEX unique_item_brand_category ON item (brand_id, category_id);

CREATE INDEX idx_item_category_price_created ON item (category_id, price, created_date);